name: "ðŸ§ª Run VM test"

on:
  push:
    paths-ignore:
      - docker/**
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - docker/**

jobs:
  check:
    name: "ðŸ§ª Run VM test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "ðŸ“¥ Checkout repository"
        uses: actions/checkout@v5

      - name: "ðŸ“¦ Install Nix"
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: "ðŸ§ª Run Nextcloud App VM tests"
        run: nix build -L .#nixosTests.nextcloud-qownnotesapi
